# Generated by Django 3.1.3 on 2020-11-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201107_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='bookid',
        ),
    ]
